<?php
declare(strict_types=1);
if (!defined('WEEKMENU')) { http_response_code(403); exit('Forbidden'); }

/**
 * Startvoorraad aan ingredienten.
 * [naam, groep, staat_in_voorraadpopup]
 *
 * Alleen items met 1 verschijnen in het "heb ik al in huis"-venster.
 * Dat houdt die lijst kort genoeg om in tien tellen af te vinken.
 */
function seedIngredients(): array
{
    return [
        // Vlees & vis
        ['gehakt',          'vlees', 1],
        ['kipfilet',        'vlees', 1],
        ['kippenpootjes',   'vlees', 1],
        ['spekblokjes',     'vlees', 1],
        ['speklapjes',      'vlees', 1],
        ['karbonade',       'vlees', 1],
        ['rookworst',       'vlees', 1],
        ['shoarmavlees',    'vlees', 1],
        ['runderlappen',    'vlees', 1],
        ['zalmfilet',       'vlees', 1],
        ['vissticks',       'vlees', 1],
        ['ham',             'vlees', 0],
        ['saucijzen',       'vlees', 0],
        ['tonijn uit blik', 'vlees', 0],

        // Basis
        ['aardappelen',  'basis', 1],
        ['pasta',        'basis', 1],
        ['macaroni',     'basis', 1],
        ['rijst',        'basis', 1],
        ['mie',          'basis', 1],
        ['wraps',        'basis', 1],
        ['eieren',       'basis', 1],
        ['stokbrood',    'basis', 0],
        ['pitabroodjes', 'basis', 0],
        ['lasagnebladen', 'basis', 0],
        ['bloem',        'basis', 0],
        ['pizzabodem',   'basis', 0],

        // Groente
        ['ui',             'groente', 1],
        ['knoflook',       'groente', 1],
        ['wortel',         'groente', 1],
        ['broccoli',       'groente', 1],
        ['bloemkool',      'groente', 1],
        ['sperziebonen',   'groente', 1],
        ['spruitjes',      'groente', 1],
        ['boerenkool',     'groente', 1],
        ['zuurkool',       'groente', 1],
        ['andijvie',       'groente', 1],
        ['rode kool',      'groente', 1],
        ['witlof',         'groente', 1],
        ['spinazie',       'groente', 1],
        ['prei',           'groente', 1],
        ['paprika',        'groente', 1],
        ['champignons',    'groente', 1],
        ['courgette',      'groente', 1],
        ['tomatenblokjes', 'groente', 1],
        ['doperwten',      'groente', 0],
        ['taugé',          'groente', 0],
        ['sla',            'groente', 0],
        ['tomaat',         'groente', 0],
        ['komkommer',      'groente', 0],
        ['appel',          'groente', 0],

        // Zuivel & rest
        ['kaas',          'rest', 1],
        ['melk',          'rest', 1],
        ['room',          'rest', 1],
        ['boter',         'rest', 1],
        ['bruine bonen',  'rest', 0],
        ['kapucijners',   'rest', 0],
        ['kidneybonen',   'rest', 0],
        ['spliterwten',   'rest', 0],
        ['tomatenpuree',  'rest', 0],
        ['kerriepoeder',  'rest', 0],
        ['nasikruiden',   'rest', 0],
        ['ketjap',        'rest', 0],
        ['satésaus',      'rest', 0],
        ['knoflooksaus',  'rest', 0],
        ['bouillonblokje', 'rest', 0],
        ['appelmoes',     'rest', 0],
    ];
}

/**
 * Startset recepten: gewone Nederlandse doordeweekse kost.
 *
 * ingredients = alleen de kenmerkende dingen. Die bepalen of een recept
 * omhoog schuift als je ze in huis hebt, en wat er op de boodschappenlijst
 * komt. Peper, zout en olie staan er dus niet tussen.
 *
 * steps = korte bereiding, één stap per regel.
 */
function seedRecipes(): array
{
    return [
        [
            'name' => 'Macaroni met gehakt',
            'category' => 'pasta', 'effort' => 1, 'weekend_only' => 0,
            'notes' => 'Klassieker. Kaas eroverheen en onder de grill.',
            'servings' => 4,
            'ingredients' => [
                ['macaroni', 400, 'g'],
                ['gehakt', 400, 'g'],
                ['tomatenblokjes', 1, 'blik'],
                ['ui', 2, null],
                ['paprika', 2, null],
                ['kaas', 100, 'g'],
            ],
            'steps' => "Kook de macaroni beetgaar volgens de verpakking.\nBak het gehakt rul met de gesnipperde ui en de paprika.\nVoeg de tomatenblokjes toe en laat 10 minuten pruttelen.\nMeng de macaroni erdoor, schep in een ovenschaal.\nKaas erover en 10 minuten onder de grill tot hij goudbruin is.",
        ],
        [
            'name' => 'Spaghetti bolognese',
            'category' => 'pasta', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['pasta', 400, 'g'],
                ['gehakt', 400, 'g'],
                ['tomatenblokjes', 1, 'blik'],
                ['ui', 2, null],
                ['knoflook', 2, 'teen'],
                ['tomatenpuree', 1, 'blik'],
                ['kaas', 100, 'g'],
            ],
            'steps' => "Fruit de ui en knoflook glazig in olie.\nBak het gehakt erbij tot het rul en bruin is.\nRoer de tomatenpuree erdoor en bak een minuut mee.\nTomatenblokjes erbij en minstens 20 minuten zachtjes laten sudderen.\nKook ondertussen de spaghetti. Serveer met geraspte kaas.",
        ],
        [
            'name' => 'Pasta carbonara',
            'category' => 'pasta', 'effort' => 1, 'weekend_only' => 0,
            'notes' => 'Haal de pan van het vuur voor je de eieren erdoor roert, anders krijg je roerei.',
            'servings' => 4,
            'ingredients' => [
                ['pasta', 400, 'g'],
                ['spekblokjes', 200, 'g'],
                ['eieren', 4, null],
                ['kaas', 75, 'g'],
                ['knoflook', 2, 'teen'],
            ],
            'steps' => "Kook de pasta. Houd een kopje kookvocht apart.\nBak de spekblokjes uit met de knoflook tot ze knapperig zijn.\nKlop de eieren los met de geraspte kaas en flink peper.\nMeng de afgegoten pasta door het spek en haal de pan van het vuur.\nRoer het eimengsel erdoor, met een scheutje kookvocht tot het romig is.",
        ],
        [
            'name' => 'Romige pasta met kip en champignons',
            'category' => 'pasta', 'effort' => 1, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['pasta', 400, 'g'],
                ['kipfilet', 500, 'g'],
                ['champignons', 250, 'g'],
                ['room', 250, 'ml'],
                ['kaas', 100, 'g'],
            ],
            'steps' => "Kook de pasta.\nSnijd de kip in blokjes en bak hem rondom gaar.\nVoeg de gesneden champignons toe en bak tot het vocht verdampt is.\nRoom erbij, laat een paar minuten indikken.\nMeng de pasta erdoor en werk af met kaas.",
        ],
        [
            'name' => 'Tonijnpasta met courgette',
            'category' => 'pasta', 'effort' => 1, 'weekend_only' => 0,
            'notes' => 'Kwartiertje werk.',
            'servings' => 4,
            'ingredients' => [
                ['pasta', 400, 'g'],
                ['tonijn uit blik', 2, 'blik'],
                ['courgette', 1, null],
                ['knoflook', 2, 'teen'],
                ['room', 250, 'ml'],
            ],
            'steps' => "Kook de pasta.\nBak de courgette in blokjes met de knoflook.\nRoer de uitgelekte tonijn en de room erdoor.\nKort laten warmen en door de pasta scheppen.",
        ],
        [
            'name' => 'Nasi goreng',
            'category' => 'rijst', 'effort' => 2, 'weekend_only' => 0,
            'notes' => 'Lekker met een gebakken ei erop.',
            'servings' => 4,
            'ingredients' => [
                ['rijst', 300, 'g'],
                ['kipfilet', 500, 'g'],
                ['eieren', 4, null],
                ['ui', 2, null],
                ['prei', 2, null],
                ['nasikruiden', 1, 'pak'],
                ['ketjap', 3, 'el'],
            ],
            'steps' => "Kook de rijst en laat hem afkoelen; koude rijst bakt veel beter.\nBak de kip in blokjes gaar en haal uit de pan.\nFruit ui en prei, voeg de nasikruiden toe en bak kort mee.\nRijst erbij, goed omscheppen, kip terug in de pan.\nAfmaken met ketjap. Bak de eieren apart en leg ze erop.",
        ],
        [
            'name' => 'Nasi met saté',
            'category' => 'rijst', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['rijst', 300, 'g'],
                ['kipfilet', 500, 'g'],
                ['satésaus', 200, 'g'],
                ['ui', 2, null],
                ['nasikruiden', 1, 'pak'],
                ['taugé', 200, 'g'],
            ],
            'steps' => "Kook de rijst en laat hem afkoelen.\nSnijd de kip in blokjes en bak hem gaar.\nFruit de ui met de nasikruiden, voeg de rijst toe.\nTaugé er op het laatst doorscheppen, die moet knapperig blijven.\nSatésaus warm maken en over de kip schenken.",
        ],
        [
            'name' => 'Kip kerrie met rijst',
            'category' => 'rijst', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['rijst', 300, 'g'],
                ['kipfilet', 500, 'g'],
                ['kerriepoeder', 2, 'tl'],
                ['ui', 2, null],
                ['room', 250, 'ml'],
                ['prei', 2, null],
            ],
            'steps' => "Kook de rijst.\nBak de kip in blokjes rondom bruin en haal uit de pan.\nFruit ui en prei, voeg het kerriepoeder toe en bak een minuut mee.\nRoom erbij, kip terug in de pan.\nLaat 10 minuten zachtjes pruttelen tot de saus gebonden is.",
        ],
        [
            'name' => 'Chili con carne met rijst',
            'category' => 'rijst', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['rijst', 300, 'g'],
                ['gehakt', 500, 'g'],
                ['kidneybonen', 1, 'blik'],
                ['tomatenblokjes', 1, 'blik'],
                ['paprika', 2, null],
                ['ui', 2, null],
            ],
            'steps' => "Bak het gehakt rul met de ui en de paprika.\nVoeg tomatenblokjes toe en kruid stevig met chilipoeder, komijn en paprikapoeder.\n20 minuten laten sudderen.\nKidneybonen erbij en nog 5 minuten meewarmen.\nServeer met gekookte rijst.",
        ],
        [
            'name' => 'Risotto met champignons',
            'category' => 'rijst', 'effort' => 3, 'weekend_only' => 0,
            'notes' => 'Vraagt roeren, dus eerder een weekendklus.',
            'servings' => 4,
            'ingredients' => [
                ['rijst', 300, 'g'],
                ['champignons', 250, 'g'],
                ['ui', 2, null],
                ['room', 100, 'ml'],
                ['kaas', 75, 'g'],
                ['bouillonblokje', 2, null],
            ],
            'steps' => "Zet een pan bouillon klaar en houd die warm.\nFruit de ui, voeg de rijst toe en bak tot de korrels glazig zijn.\nSchep steeds een pollepel bouillon erbij en roer tot die is opgenomen.\nBak ondertussen de champignons apart goudbruin.\nNa 18 tot 20 minuten de champignons, room en kaas erdoor.",
        ],
        [
            'name' => 'Bami goreng',
            'category' => 'noedels', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['mie', 250, 'g'],
                ['kipfilet', 500, 'g'],
                ['prei', 2, null],
                ['taugé', 200, 'g'],
                ['ketjap', 3, 'el'],
                ['eieren', 2, null],
            ],
            'steps' => "Kook de mie kort en spoel koud.\nBak de kip in blokjes gaar.\nVoeg prei toe en roerbak een paar minuten.\nMie erbij, ketjap eroverheen en goed omscheppen.\nTaugé op het laatst erdoor. Bak de eieren apart.",
        ],
        [
            'name' => 'Roerbakgroenten met kip en mie',
            'category' => 'noedels', 'effort' => 1, 'weekend_only' => 0,
            'notes' => 'Alles in één wok.',
            'servings' => 4,
            'ingredients' => [
                ['mie', 250, 'g'],
                ['kipfilet', 500, 'g'],
                ['paprika', 2, null],
                ['broccoli', 1, null],
                ['ketjap', 3, 'el'],
                ['knoflook', 2, 'teen'],
            ],
            'steps' => "Kook de mie volgens de verpakking.\nRoerbak de kip in blokjes met de knoflook.\nBroccoliroosjes en paprika erbij, 5 minuten roerbakken; ze mogen knapperig blijven.\nMie en ketjap erdoor scheppen en kort meewarmen.",
        ],
        [
            'name' => 'Boerenkoolstamppot met rookworst',
            'category' => 'stamppot', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['boerenkool', 800, 'g'],
                ['aardappelen', 1000, 'g'],
                ['rookworst', 1, null],
                ['spekblokjes', 150, 'g'],
                ['melk', 200, 'ml'],
            ],
            'steps' => "Kook de aardappelen met de boerenkool erbovenop in 20 minuten gaar.\nVerwarm de rookworst mee in de pan of apart in water.\nBak de spekblokjes knapperig uit.\nGiet af en stamp met een scheut warme melk en een klont boter.\nSpek erdoor en de rookworst erbij serveren.",
        ],
        [
            'name' => 'Hutspot met klapstuk',
            'category' => 'stamppot', 'effort' => 3, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['wortel', 750, 'g'],
                ['ui', 250, 'g'],
                ['aardappelen', 1000, 'g'],
                ['runderlappen', 600, 'g'],
                ['boter', 50, 'g'],
            ],
            'steps' => "Kook het klapstuk in ruim water met wat zout in 2 uur zacht.\nKook aardappelen, wortel en ui samen in 20 minuten gaar.\nGiet af en stamp met boter tot een grove stamppot.\nSnijd het vlees in stukken en serveer erbij met wat kookvocht.",
        ],
        [
            'name' => 'Zuurkoolstamppot met spek',
            'category' => 'stamppot', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['zuurkool', 700, 'g'],
                ['aardappelen', 1000, 'g'],
                ['spekblokjes', 150, 'g'],
                ['rookworst', 1, null],
                ['melk', 200, 'ml'],
            ],
            'steps' => "Kook de aardappelen gaar.\nBak de spekblokjes uit tot ze knapperig zijn.\nVerwarm de rookworst.\nStamp de aardappelen met melk en boter, roer de zuurkool erdoor.\nSpek erover en de worst erbij.",
        ],
        [
            'name' => 'Andijviestamppot',
            'category' => 'stamppot', 'effort' => 1, 'weekend_only' => 0,
            'notes' => 'Rauwe andijvie door de warme puree.',
            'servings' => 4,
            'ingredients' => [
                ['andijvie', 600, 'g'],
                ['aardappelen', 1000, 'g'],
                ['spekblokjes', 150, 'g'],
                ['melk', 200, 'ml'],
            ],
            'steps' => "Kook de aardappelen gaar.\nBak ondertussen de spekblokjes knapperig.\nStamp de aardappelen met warme melk en boter.\nRoer de fijngesneden rauwe andijvie erdoor; die slinkt in de warme puree.\nSpek erdoor en meteen opdienen.",
        ],
        [
            'name' => 'Spinaziestamppot met ei',
            'category' => 'stamppot', 'effort' => 1, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['spinazie', 600, 'g'],
                ['aardappelen', 1000, 'g'],
                ['eieren', 4, null],
                ['melk', 200, 'ml'],
                ['kaas', 75, 'g'],
            ],
            'steps' => "Kook de aardappelen gaar en de eieren hard in 8 minuten.\nLaat de spinazie in een pan slinken en knijp het vocht eruit.\nStamp de aardappelen met melk en boter.\nSpinazie en geraspte kaas erdoor.\nServeer met de gehalveerde eieren erop.",
        ],
        [
            'name' => 'Gehaktballen met aardappelen en groente',
            'category' => 'aardappel', 'effort' => 2, 'weekend_only' => 0,
            'notes' => 'Het klassieke AVG-tje.',
            'servings' => 4,
            'ingredients' => [
                ['gehakt', 500, 'g'],
                ['aardappelen', 1000, 'g'],
                ['sperziebonen', 500, 'g'],
                ['ui', 2, null],
                ['appelmoes', 1, 'pot'],
            ],
            'steps' => "Meng het gehakt met ei, paneermeel, fijne ui, zout en peper.\nDraai er ballen van en bak ze rondom bruin.\nZet het vuur laag en laat ze met deksel 20 minuten garen.\nKook ondertussen de aardappelen en de sperziebonen.\nServeer met de jus uit de pan en een schep appelmoes.",
        ],
        [
            'name' => 'Kipfilet met krieltjes en sperziebonen',
            'category' => 'aardappel', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['kipfilet', 500, 'g'],
                ['aardappelen', 1000, 'g'],
                ['sperziebonen', 500, 'g'],
                ['boter', 50, 'g'],
            ],
            'steps' => "Kook de krieltjes 10 minuten voor en bak ze daarna goudbruin in boter.\nKook de sperziebonen in 8 minuten beetgaar.\nBak de kipfilet op middelhoog vuur in 6 minuten per kant gaar.\nLaat de kip even rusten voor je hem aansnijdt.",
        ],
        [
            'name' => 'Karbonade met bloemkool en aardappelen',
            'category' => 'aardappel', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['karbonade', 4, null],
                ['bloemkool', 1, null],
                ['aardappelen', 1000, 'g'],
                ['boter', 50, 'g'],
            ],
            'steps' => "Kook de aardappelen gaar.\nKook de bloemkoolroosjes in 12 minuten beetgaar.\nBak de karbonades in boter op hoog vuur rondom bruin.\nVuur laag, deksel erop, nog 10 minuten garen.\nBlus de pan af met een scheutje water voor de jus.",
        ],
        [
            'name' => 'Bloemkool met gehakt en aardappelen',
            'category' => 'aardappel', 'effort' => 1, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['bloemkool', 1, null],
                ['gehakt', 400, 'g'],
                ['aardappelen', 1000, 'g'],
                ['kaas', 75, 'g'],
            ],
            'steps' => "Kook de aardappelen en de bloemkool gaar.\nBak het gehakt rul en kruid het stevig.\nSchep alles om in een schaal, kaas erover.\nKort onder de grill tot de kaas gesmolten is.",
        ],
        [
            'name' => 'Vissticks met puree en worteltjes',
            'category' => 'aardappel', 'effort' => 1, 'weekend_only' => 0,
            'notes' => 'Altijd goed bij de kinderen.',
            'servings' => 4,
            'ingredients' => [
                ['vissticks', 12, null],
                ['aardappelen', 1000, 'g'],
                ['wortel', 500, 'g'],
                ['melk', 200, 'ml'],
            ],
            'steps' => "Kook de aardappelen gaar en stamp ze met warme melk en boter.\nKook de wortel in 10 minuten beetgaar.\nBak of oven de vissticks volgens de verpakking.\nServeer met een schijfje citroen.",
        ],
        [
            'name' => 'Speklapjes met sperziebonen en aardappelen',
            'category' => 'aardappel', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['speklapjes', 4, null],
                ['sperziebonen', 500, 'g'],
                ['aardappelen', 1000, 'g'],
                ['ui', 2, null],
            ],
            'steps' => "Kook de aardappelen en de sperziebonen.\nBak de speklapjes op middelhoog vuur rustig bruin; te hoog vuur maakt ze taai.\nHaal ze uit de pan en fruit de ui in het achtergebleven vet.\nSchenk de ui met het bakvet over het vlees.",
        ],
        [
            'name' => 'Spruitjes met aardappelen en spek',
            'category' => 'aardappel', 'effort' => 1, 'weekend_only' => 0,
            'notes' => 'Niet te lang koken, dan worden ze bitter.',
            'servings' => 4,
            'ingredients' => [
                ['spruitjes', 600, 'g'],
                ['aardappelen', 1000, 'g'],
                ['spekblokjes', 150, 'g'],
            ],
            'steps' => "Kook de aardappelen gaar.\nKook de spruitjes in 10 tot 12 minuten beetgaar, niet langer.\nBak de spekblokjes knapperig uit.\nSchep de spruitjes door het spek met een klont boter.",
        ],
        [
            'name' => 'Rode kool met appeltjes en worst',
            'category' => 'aardappel', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['rode kool', 800, 'g'],
                ['appel', 2, null],
                ['aardappelen', 1000, 'g'],
                ['rookworst', 1, null],
            ],
            'steps' => "Doe de rode kool met de appel in stukken en een scheut water in een pan.\nVoeg een laurierblad en een paar kruidnagels toe.\n30 minuten met deksel zachtjes stoven.\nKook de aardappelen en verwarm de rookworst.",
        ],
        [
            'name' => 'Broccoli met aardappelen en kaassaus',
            'category' => 'aardappel', 'effort' => 1, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['broccoli', 1, null],
                ['aardappelen', 1000, 'g'],
                ['kaas', 150, 'g'],
                ['melk', 500, 'ml'],
                ['ham', 100, 'g'],
            ],
            'steps' => "Kook de aardappelen en de broccoli beetgaar.\nSmelt boter, roer er bloem door en schenk beetje bij beetje melk erbij.\nBlijf roeren tot de saus bindt, dan de kaas erdoor laten smelten.\nHam in reepjes door de saus en over de groente schenken.",
        ],
        [
            'name' => 'Prei-aardappelschotel met gehakt',
            'category' => 'oven', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['prei', 3, null],
                ['aardappelen', 1000, 'g'],
                ['gehakt', 400, 'g'],
                ['kaas', 100, 'g'],
                ['room', 200, 'ml'],
            ],
            'steps' => "Verwarm de oven voor op 200 graden.\nKook de aardappelen gaar en snijd ze in plakken.\nBak het gehakt rul, voeg de prei in ringen toe en bak tot die zacht is.\nLaag om laag in een schaal, room eroverheen, kaas erop.\n25 minuten in de oven tot de bovenkant goudbruin is.",
        ],
        [
            'name' => 'Ovenschotel met aardappel en broccoli',
            'category' => 'oven', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['aardappelen', 1000, 'g'],
                ['broccoli', 1, null],
                ['gehakt', 400, 'g'],
                ['kaas', 100, 'g'],
                ['room', 250, 'ml'],
            ],
            'steps' => "Verwarm de oven voor op 200 graden.\nKook de aardappelen en de broccoli beetgaar.\nBak het gehakt rul en kruid het.\nAlles in een schaal, room erover, afdekken met kaas.\n25 minuten in de oven.",
        ],
        [
            'name' => 'Lasagne',
            'category' => 'oven', 'effort' => 3, 'weekend_only' => 0,
            'notes' => 'Even werk, maar je eet er twee dagen van.',
            'servings' => 4,
            'ingredients' => [
                ['lasagnebladen', 250, 'g'],
                ['gehakt', 500, 'g'],
                ['tomatenblokjes', 1, 'blik'],
                ['kaas', 150, 'g'],
                ['room', 500, 'ml'],
                ['ui', 2, null],
            ],
            'steps' => "Maak een bolognesesaus van gehakt, ui en tomatenblokjes; 30 minuten laten sudderen.\nMaak een bechamel van boter, bloem en melk, of gebruik room.\nVerwarm de oven voor op 180 graden.\nStapel om en om saus, lasagnebladen en bechamel; eindig met bechamel.\nKaas erover en 40 minuten in de oven. Laat hem 10 minuten staan voor het snijden.",
        ],
        [
            'name' => 'Macaroni-ovenschotel',
            'category' => 'oven', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['macaroni', 400, 'g'],
                ['gehakt', 400, 'g'],
                ['tomatenblokjes', 1, 'blik'],
                ['kaas', 100, 'g'],
                ['paprika', 2, null],
            ],
            'steps' => "Verwarm de oven voor op 200 graden.\nKook de macaroni net niet gaar; hij gaart in de oven door.\nBak het gehakt rul met de paprika, tomatenblokjes erbij.\nMeng met de macaroni in een ovenschaal, kaas erover.\n20 minuten in de oven.",
        ],
        [
            'name' => 'Witlof met ham en kaas uit de oven',
            'category' => 'oven', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['witlof', 8, null],
                ['ham', 8, null],
                ['kaas', 150, 'g'],
                ['aardappelen', 1000, 'g'],
                ['melk', 500, 'ml'],
            ],
            'steps' => "Kook de witlof in 12 minuten gaar en laat hem goed uitlekken.\nRol elke stronk in een plak ham.\nLeg ze in een ingevette schaal.\nMaak een kaassaus van boter, bloem, melk en kaas en schenk eroverheen.\n20 minuten op 200 graden. Serveer met gekookte aardappelen.",
        ],
        [
            'name' => 'Kippenpootjes uit de oven met krieltjes',
            'category' => 'oven', 'effort' => 2, 'weekend_only' => 0,
            'notes' => 'Alles op één plaat, dus weinig afwas.',
            'servings' => 4,
            'ingredients' => [
                ['kippenpootjes', 8, null],
                ['aardappelen', 1000, 'g'],
                ['paprika', 2, null],
                ['ui', 2, null],
            ],
            'steps' => "Verwarm de oven voor op 200 graden.\nMeng krieltjes, paprika en ui met olie, paprikapoeder, zout en peper.\nSpreid uit op een bakplaat en leg de kippenpootjes ertussen.\n45 minuten in de oven; keer alles halverwege om.",
        ],
        [
            'name' => 'Zelfgemaakte pizza',
            'category' => 'oven', 'effort' => 2, 'weekend_only' => 0,
            'notes' => 'Iedereen belegt zijn eigen helft.',
            'servings' => 4,
            'ingredients' => [
                ['pizzabodem', 4, null],
                ['tomatenpuree', 1, 'blik'],
                ['kaas', 200, 'g'],
                ['paprika', 2, null],
                ['champignons', 150, 'g'],
                ['ham', 100, 'g'],
            ],
            'steps' => "Verwarm de oven zo heet mogelijk voor, minstens 220 graden.\nBestrijk de bodem dun met tomatenpuree en wat oregano.\nBeleg met kaas en de rest; niet te veel, anders wordt hij zompig.\n12 tot 15 minuten bakken tot de randen bruin zijn.",
        ],
        [
            'name' => 'Griekse ovenschotel met gehakt',
            'category' => 'oven', 'effort' => 3, 'weekend_only' => 1,
            'notes' => 'Weekendwerk.',
            'servings' => 4,
            'ingredients' => [
                ['gehakt', 500, 'g'],
                ['aardappelen', 1000, 'g'],
                ['courgette', 1, null],
                ['tomatenblokjes', 1, 'blik'],
                ['kaas', 100, 'g'],
                ['room', 200, 'ml'],
            ],
            'steps' => "Snijd aardappel en courgette in plakken en bak ze kort aan.\nBak het gehakt met ui, kaneel en oregano, tomatenblokjes erbij.\nLaat de saus 20 minuten indikken.\nLaag om laag stapelen, afwerken met room en kaas.\n40 minuten op 180 graden.",
        ],
        [
            'name' => 'Erwtensoep met roggebrood',
            'category' => 'soep', 'effort' => 3, 'weekend_only' => 1,
            'notes' => 'Maak een grote pan, wordt de volgende dag beter.',
            'servings' => 4,
            'ingredients' => [
                ['spliterwten', 500, 'g'],
                ['rookworst', 1, null],
                ['wortel', 500, 'g'],
                ['prei', 2, null],
                ['aardappelen', 500, 'g'],
                ['bouillonblokje', 2, null],
            ],
            'steps' => "Zet de spliterwten op met ruim water en bouillon; breng aan de kook.\nSchuim af en laat 45 minuten koken tot de erwten uit elkaar vallen.\nVoeg aardappel, wortel en prei toe en kook nog 30 minuten.\nSnijd de rookworst in plakken en warm die de laatste 10 minuten mee.\nServeer met roggebrood en katenspek.",
        ],
        [
            'name' => 'Tomatensoep met stokbrood',
            'category' => 'soep', 'effort' => 1, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['tomatenblokjes', 2, 'blik'],
                ['gehakt', 250, 'g'],
                ['ui', 2, null],
                ['bouillonblokje', 2, null],
                ['stokbrood', 1, null],
            ],
            'steps' => "Draai kleine balletjes van het gehakt.\nFruit de ui, voeg tomatenblokjes en bouillon toe.\n15 minuten laten trekken en pureren als je hem glad wilt.\nBalletjes erin en 10 minuten zachtjes gaar laten worden.\nServeer met warm stokbrood.",
        ],
        [
            'name' => 'Groentesoep met balletjes',
            'category' => 'soep', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['wortel', 500, 'g'],
                ['prei', 2, null],
                ['gehakt', 250, 'g'],
                ['bouillonblokje', 2, null],
                ['stokbrood', 1, null],
            ],
            'steps' => "Zet ruim bouillon op.\nDraai kleine balletjes van het gehakt en laat ze in de bouillon gaar worden.\nVoeg wortel en prei in kleine stukjes toe.\n15 minuten zachtjes koken tot de groente gaar is.\nServeer met stokbrood.",
        ],
        [
            'name' => 'Wraps met kip',
            'category' => 'wraps', 'effort' => 1, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['wraps', 8, null],
                ['kipfilet', 500, 'g'],
                ['paprika', 2, null],
                ['sla', 1, null],
                ['tomaat', 2, null],
                ['kaas', 100, 'g'],
            ],
            'steps' => "Snijd de kip in reepjes en bak hem gaar met paprika en wat kruiden.\nWarm de wraps kort in een droge koekenpan.\nBeleg met sla, tomaat, de kip en geraspte kaas.\nRol op en snijd schuin doormidden.",
        ],
        [
            'name' => 'Shoarma met pita en knoflooksaus',
            'category' => 'wraps', 'effort' => 1, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['shoarmavlees', 500, 'g'],
                ['pitabroodjes', 8, null],
                ['knoflooksaus', 100, 'ml'],
                ['sla', 1, null],
                ['tomaat', 2, null],
                ['komkommer', 1, null],
            ],
            'steps' => "Bak het shoarmavlees op hoog vuur rondom gaar.\nWarm de pitabroodjes in de oven of de broodrooster.\nSnijd sla, tomaat en komkommer klein.\nVul de broodjes met vlees, groente en knoflooksaus.",
        ],
        [
            'name' => 'Hamburgers met salade en aardappelpartjes',
            'category' => 'wraps', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['gehakt', 600, 'g'],
                ['aardappelen', 1000, 'g'],
                ['sla', 1, null],
                ['tomaat', 2, null],
                ['kaas', 100, 'g'],
                ['ui', 2, null],
            ],
            'steps' => "Verwarm de oven voor op 200 graden.\nSnijd de aardappelen in partjes, meng met olie en paprikapoeder, 35 minuten in de oven.\nDraai platte burgers van het gehakt en kruid ze.\nBak ze 4 minuten per kant; leg de laatste minuut kaas erop.\nServeer met een simpele salade van sla, tomaat en ui.",
        ],
        [
            'name' => 'Hachee met rode kool',
            'category' => 'vlees', 'effort' => 3, 'weekend_only' => 1,
            'notes' => 'Uren sudderen, dus voor het weekend.',
            'servings' => 4,
            'ingredients' => [
                ['runderlappen', 800, 'g'],
                ['ui', 500, 'g'],
                ['rode kool', 800, 'g'],
                ['aardappelen', 1000, 'g'],
                ['bouillonblokje', 2, null],
            ],
            'steps' => "Snijd het vlees in blokjes en bak ze rondom bruin.\nHaal het vlees eruit en fruit een flinke hoeveelheid ui in het vet.\nVlees terug, bouillon, laurier, kruidnagel en een scheut azijn erbij.\nMinstens 2,5 uur op heel laag vuur laten sudderen.\nServeer met rode kool en aardappelen.",
        ],
        [
            'name' => 'Draadjesvlees met aardappelen',
            'category' => 'vlees', 'effort' => 3, 'weekend_only' => 1,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['runderlappen', 800, 'g'],
                ['ui', 250, 'g'],
                ['aardappelen', 1000, 'g'],
                ['boter', 50, 'g'],
                ['bouillonblokje', 2, null],
            ],
            'steps' => "Bak de lappen in boter rondom bruin.\nVoeg ui, bouillon, laurier en kruidnagel toe.\n3 uur op het laagste vuur met deksel laten staan.\nHet vlees is klaar als het uit elkaar valt.\nBind de jus eventueel en serveer met aardappelen.",
        ],
        [
            'name' => 'Saucijzen met zuurkool',
            'category' => 'vlees', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['saucijzen', 4, null],
                ['zuurkool', 700, 'g'],
                ['aardappelen', 1000, 'g'],
                ['spekblokjes', 150, 'g'],
            ],
            'steps' => "Bak de saucijzen rustig rondom bruin en laat ze met deksel 20 minuten garen.\nKook de aardappelen.\nWarm de zuurkool met de uitgebakken spekblokjes.\nServeer met de jus uit de saucijzenpan.",
        ],
        [
            'name' => 'Zalmfilet met puree en spinazie',
            'category' => 'vis', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['zalmfilet', 4, null],
                ['aardappelen', 1000, 'g'],
                ['spinazie', 600, 'g'],
                ['room', 100, 'ml'],
                ['melk', 200, 'ml'],
            ],
            'steps' => "Kook de aardappelen en stamp ze met warme melk en boter.\nLaat de spinazie slinken en roer er een scheut room door.\nBak de zalm 3 tot 4 minuten op de huid, draai hem om en haal de pan van het vuur.\nDe zalm gaart na; hij mag vanbinnen net glazig blijven.",
        ],
        [
            'name' => 'Bruine bonen met spek',
            'category' => 'bonen', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['bruine bonen', 1, 'blik'],
                ['spekblokjes', 150, 'g'],
                ['ui', 2, null],
                ['aardappelen', 1000, 'g'],
            ],
            'steps' => "Bak de spekblokjes uit met de gesnipperde ui.\nVoeg de uitgelekte bruine bonen toe.\nKruid met wat azijn, stroop of mosterd naar smaak.\n10 minuten zachtjes warmen. Serveer met gekookte aardappelen.",
        ],
        [
            'name' => 'Kapucijners met spek en zilveruitjes',
            'category' => 'bonen', 'effort' => 2, 'weekend_only' => 0,
            'notes' => null,
            'servings' => 4,
            'ingredients' => [
                ['kapucijners', 1, 'blik'],
                ['spekblokjes', 150, 'g'],
                ['ui', 2, null],
                ['aardappelen', 1000, 'g'],
            ],
            'steps' => "Bak de spekblokjes knapperig uit.\nWarm de uitgelekte kapucijners door.\nServeer met zilveruitjes, augurk, piccalilly en gekookte aardappelen.\nIedereen schept zelf op wat hij wil.",
        ],
        [
            'name' => 'Pannenkoeken',
            'category' => 'overig', 'effort' => 1, 'weekend_only' => 0,
            'notes' => 'Avondje niet koken.',
            'servings' => 4,
            'ingredients' => [
                ['bloem', 250, 'g'],
                ['melk', 500, 'ml'],
                ['eieren', 3, null],
                ['spekblokjes', 200, 'g'],
                ['boter', 50, 'g'],
            ],
            'steps' => "Klop bloem, eieren, melk en een snuf zout tot een glad beslag.\nLaat het beslag een half uur rusten; dat scheelt echt.\nBak de spekblokjes vast uit in de pan en schenk er beslag overheen.\nBak op middelhoog vuur, keer als de bovenkant droog is.",
        ],
    ];
}

/**
 * Seizoen per meegeleverd recept: maanden (1-12) waarin het in de loting
 * mag. Niet genoemd = het hele jaar. Wordt eenmalig gezet door install.php
 * en door upgrade.php op het moment dat de kolom erbij komt; daarna is het
 * van jou en pas je het aan in Recepten beheren.
 */
function seedSeasons(): array
{
    $winter = '1,2,3,10,11,12';            // oktober t/m maart
    $koud   = '1,2,3,4,9,10,11,12';        // september t/m april
    $zomer  = '5,6,7,8,9';                 // mei t/m september

    return [
        'Boerenkoolstamppot met rookworst'  => $winter,
        'Hutspot met klapstuk'              => $winter,
        'Zuurkoolstamppot met spek'         => $winter,
        'Andijviestamppot'                  => $koud,
        'Spinaziestamppot met ei'           => $koud,
        'Erwtensoep met roggebrood'         => $winter,
        'Hachee met rode kool'              => $winter,
        'Draadjesvlees met aardappelen'     => $winter,
        'Saucijzen met zuurkool'            => $winter,
        'Rode kool met appeltjes en worst'  => $winter,
        'Spruitjes met aardappelen en spek' => $winter,
        'Witlof met ham en kaas uit de oven' => $winter,
        'Bruine bonen met spek'             => $koud,
        'Kapucijners met spek en zilveruitjes' => $koud,
        'Groentesoep met balletjes'         => $koud,
        'Tonijnpasta met courgette'         => $zomer,
        'Hamburgers met salade en aardappelpartjes' => $zomer,
    ];
}
